plugins {
    id 'com.android.application'
}

android {
    namespace 'com.promusic.app'
    compileSdk 33

    defaultConfig {
        applicationId "com.promusic.app"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++14"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
    // C++ Library များကို ချိတ်ဆက်ရန် ခွင့်ပြုခြင်း
    buildFeatures {
        prefab true 
    }
}

dependencies {
    // Google ၏ Oboe Library ကို ထည့်သွင်းခြင်း
    implementation 'com.google.oboe:oboe:1.7.0'
}
